### ISSUE TITLE
Java 17 fails to build

### ISSUE THREAD

**Issue by leadnateniride** [61c-teach/venus#2]
I am trying to build the venus. 

I finally figured out that because right now the gradle version is not high enough (even after https://github.com/61c-teach/venus/commit/24e6d8996463af20decd1e455ee539025ad9ade8).

In the release note in Gradle 7.3,

> In previous Gradle versions (<7.3), running Gradle itself on Java 17 resulted in an error. 

I tried to install a Java 11 and built it successfully. 

Hope this can help people who want to build the venus.

**Comment by chrononyan** [comment]
Yeah, Java ecosystem's cross-version compatibility isn't super great, and the project isn't very actively maintained... Closing because there's nothing to do here, but glad you figured it out.
